version: '3'

services:
  azuresqledge:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: azuresqledge
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=Faruk.123
    cap_add:
      - SYS_PTRACE

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmqcontainer
    ports:
      - "15672:15672"
      - "5672:5672"

  systemcase.notification:
    image: systemcase.notification
    build:
      context: .
      dockerfile: SystemCase.Notification/Dockerfile

  systemcase.api:
    image: systemcase.api
    build:
      context: .
      dockerfile: SystemCase.Api/Dockerfile
